genesis-file="/initialization/genesis-besu.json"
data-path="/opt/besu/data"
data-storage-format="BONSAI"
sync-mode="FULL"
sync-min-peers=0
p2p-enabled=false
host-allowlist=["*"]
revert-reason-enabled=true

target-gas-limit=30000000
min-gas-price=0
tx-pool-min-gas-price=0
strict-tx-replay-protection-enabled=false

engine-rpc-enabled=true
engine-host-allowlist=["*"]
engine-rpc-port=8550
engine-jwt-disabled=true

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ETH","NET","WEB3","DEBUG"]
rpc-http-cors-origins=["*"]

metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# Use the shared Besu package without its zkEVM plugins.
Xplugins-external-enabled=false
