[package]
name = "guest-crypto"
version = "0.1.0"
edition = "2021"

[lib]
name = "guest_crypto"
crate-type = ["staticlib"]

[dependencies]
ark-bls12-381 = { version = "0.6", default-features = false, features = ["curve"] }
ark-ec = { version = "0.6", default-features = false }
ark-ff = { version = "0.6", default-features = false }
ark-serialize = { version = "0.6", default-features = false }
k256 = { version = "0.13", default-features = false, features = ["ecdsa", "arithmetic"] }
revm-precompile = { version = "43.0.1", default-features = false }

[dev-dependencies]
hex = "0.4"
sha3 = "0.10"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[profile.dev]
panic = "abort"
