package codegen

import (
	"fmt"
	"io"
	"sort"
	"text/template"

	"github.com/consensys/gnark-crypto/field/koalabear"
	"github.com/consensys/linea-monorepo/prover-ray/crypto/koalabear/fri"
	"github.com/consensys/linea-monorepo/prover-ray/maths/koalabear/field"
)

// WriteFRISpecZig writes generated Zig source containing comptime-consumable
// FRI spec constants: params, layout, and dq_layout. It emits data only; no
// control flow is generated.
func WriteFRISpecZig(w io.Writer, params fri.Params, layout Layout, dq DQLayout) error {
	tmpl, err := template.New("fri_spec").Funcs(template.FuncMap{
		"domainGenInits":    domainGenInits,
		"domainGenInvInits": domainGenInvInits,
		"intArray":          intArray,
		"railLit":           railLiteral,
		"zigStr":            zigString,
	}).Parse(friSpecTemplate)
	if err != nil {
		return err
	}

	data := friSpecTemplateData{
		Params: params,
		Layout: friSpecLayout(layout),
		DQ:     dq,
	}
	return tmpl.Execute(w, data)
}

// friSpecLayout converts a Layout into a sorted, template-ready form.
// Slots are sorted by name for deterministic output.
type friSpecNamedSlot struct {
	Name    string
	TreeIdx int
	PolyIdx int
	Rail    field.Kind
}

type friSpecLayoutData struct {
	Layout
	ColSlotsSorted      []friSpecNamedSlot
	AirChunkSlotsSorted []friSpecNamedSlot
}

func friSpecLayout(l Layout) friSpecLayoutData {
	col := make([]friSpecNamedSlot, 0, len(l.ColSlots))
	for name, slot := range l.ColSlots {
		col = append(col, friSpecNamedSlot{name, slot.TreeIdx, slot.PolyIdx, slot.Rail})
	}
	sort.Slice(col, func(i, j int) bool { return col[i].Name < col[j].Name })

	air := make([]friSpecNamedSlot, 0, len(l.AirChunkSlots))
	for name, slot := range l.AirChunkSlots {
		air = append(air, friSpecNamedSlot{name, slot.TreeIdx, slot.PolyIdx, slot.Rail})
	}
	sort.Slice(air, func(i, j int) bool { return air[i].Name < air[j].Name })

	return friSpecLayoutData{Layout: l, ColSlotsSorted: col, AirChunkSlotsSorted: air}
}

type friSpecTemplateData struct {
	Params fri.Params
	Layout friSpecLayoutData
	DQ     DQLayout
}

func domainGenInits(domains []fri.DomainLight) string {
	out := "&[_]field.Element{"
	for i, domain := range domains {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf(" field.Element.init(%d)", domain.Generator.Uint64())
	}
	return out + " }"
}

func domainGenInvInits(domains []fri.DomainLight) string {
	out := "&[_]field.Element{"
	for i, domain := range domains {
		if i > 0 {
			out += ", "
		}
		var inv koalabear.Element
		inv.Inverse(&domain.Generator)
		out += fmt.Sprintf(" field.Element.init(%d)", inv.Uint64())
	}
	return out + " }"
}

func railLiteral(r field.Kind) string {
	if r == field.KindExt {
		return ".ext"
	}
	return ".base"
}

const friSpecTemplate = `// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.

const verifier_ray = @import("verifier_ray");
const fri_types = verifier_ray.fri.types;
const fri_spec = verifier_ray.fri.spec;
const field = verifier_ray.field.koalabear;

pub const params = fri_types.Params{
    .n = {{.Params.N}},
    .d = {{.Params.D}},
    .num_queries = {{.Params.NumQueries}},
    .num_rounds = {{.Params.NumRounds}},
    .domain_gens = {{domainGenInits .Params.DomainsLight}},
    .domain_gens_inv = {{domainGenInvInits .Params.DomainsLight}},
    .grinding = {{.Params.Grinding}},
};

const layout_col_slots = [_]fri_spec.NamedSlot{
{{range .Layout.ColSlotsSorted}}    .{ .name = "{{zigStr .Name}}", .slot = .{ .tree_idx = {{.TreeIdx}}, .poly_idx = {{.PolyIdx}}, .rail = {{railLit .Rail}} } },
{{end}}};
const layout_air_chunk_slots = [_]fri_spec.NamedSlot{
{{range .Layout.AirChunkSlotsSorted}}    .{ .name = "{{zigStr .Name}}", .slot = .{ .tree_idx = {{.TreeIdx}}, .poly_idx = {{.PolyIdx}}, .rail = {{railLit .Rail}} } },
{{end}}};
const layout_trace_begin = [_]u32{{intArray .Layout.TraceBegin}};
const layout_trace_end = [_]u32{{intArray .Layout.TraceEnd}};
const layout_tree_size = [_]u32{{intArray .Layout.TreeSizes}};

pub const layout = fri_spec.Layout{
    .num_trees = {{.Layout.NumTrees}},
    .setup_begin = {{.Layout.SetupBegin}},
    .setup_end = {{.Layout.SetupEnd}},
    .trace_begin = &layout_trace_begin,
    .trace_end = &layout_trace_end,
    .air_begin = {{.Layout.AirBegin}},
    .air_end = {{.Layout.AirEnd}},
    .tree_size = &layout_tree_size,
    .col_slots = &layout_col_slots,
    .air_chunk_slots = &layout_air_chunk_slots,
};

{{range $levelI, $lv := .DQ.Levels}}
const dq_level_{{$levelI}}_shifts = [_]u32{{intArray $lv.Shifts}};
{{range $groupI, $cols := $lv.ColGroups}}const dq_level_{{$levelI}}_col_group_{{$groupI}} = [_]fri_spec.ColRef{
{{range $cols}}    .{ .name = "{{zigStr .Name}}", .key = "{{zigStr .Key}}" },
{{end}}};
{{end}}const dq_level_{{$levelI}}_col_groups = [_][]const fri_spec.ColRef{
{{range $groupI, $cols := $lv.ColGroups}}    &dq_level_{{$levelI}}_col_group_{{$groupI}},
{{end}}};
const dq_level_{{$levelI}}_air_chunks = [_][]const u8{
{{range $lv.AirChunks}}    "{{zigStr .}}",
{{end}}};
{{end}}const dq_levels = [_]fri_spec.DQLevel{
{{range $levelI, $lv := .DQ.Levels}}    .{ .size = {{$lv.Size}}, .shifts = &dq_level_{{$levelI}}_shifts, .col_groups = &dq_level_{{$levelI}}_col_groups, .air_chunks = &dq_level_{{$levelI}}_air_chunks },
{{end}}};

pub const dq_layout = fri_spec.DQLayout{
    .levels = &dq_levels,
};
`
