package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/maths/koalabear/field"
)

// PcsZigOptions configures imports and the constant naming for a generated Zig
// pcs.System (current-branch engine, src/query/pcs.zig). The default imports
// assume the standard verifier-ray source layout; multi-system files set
// EmitHeader=false and provide qualified imports.
type PcsZigOptions struct {
	// PcsImport is the Zig module exposing `System` / `SizeBundle` / `DeepEntry`
	// / `ClaimRef` / `BatchRoot` (the current engine, `src/query/pcs.zig`).
	// FriImport exposes `Params`. When empty, verifier-ray-relative defaults are
	// used.
	PcsImport string
	FriImport string
	// FieldImport is used only to emit a precomputed-batch root octuplet literal
	// (the rare precomputed-batch path); its `.Digest` / raw-u32 form is emitted
	// inline as a [8]u32. Empty → verifier-ray default.
	FieldImport string
	// ConstName is the name of the emitted `System` const. Empty → "pcs_system".
	ConstName string
	// ConstPrefix namespaces the supporting consts (params/layout/…), so several
	// PCS systems can coexist in one file. Empty → no prefix.
	ConstPrefix string
	// EmitHeader, when true, prepends the import declarations. Set false when
	// several systems share one file header.
	EmitHeader bool
}

func defaultPcsZigOptions() PcsZigOptions {
	return PcsZigOptions{
		PcsImport:   `@import("../query/pcs.zig")`,
		FriImport:   `@import("../query/fri.zig")`,
		FieldImport: `@import("../field/koalabear.zig")`,
		ConstName:   "pcs_system",
		EmitHeader:  true,
	}
}

// WritePcsSystemZig writes the Zig source for one PcsSystem as a literal
// `pcs.System` for the current-branch engine: FRI params, the EXPLICIT canonical
// layout (`[]const SizeBundle` with per-entry `entry_idx`), the witness/quotient
// claim maps, the batch-root provenances, and the zeta coin index.
//
// Unlike the fri-pcs branch (which emitted per-batch shapes/shifts and let Zig's
// buildLayout reconstruct the layout), this engine has no buildLayout: the layout
// is materialized here from PcsSystem.Layout, with each DeepEntry's flat
// entry_idx already assigned by computePcsLayout.
//
// The emitted `<ConstName>` const is a `pcs.System` ready to drop into a
// `verifier.Systems{ .pcs = ... }`.
func WritePcsSystemZig(w io.Writer, index int, system PcsSystem, opts PcsZigOptions) error {
	def := defaultPcsZigOptions()
	if opts.PcsImport == "" {
		opts.PcsImport = def.PcsImport
	}
	if opts.FriImport == "" {
		opts.FriImport = def.FriImport
	}
	if opts.FieldImport == "" {
		opts.FieldImport = def.FieldImport
	}
	if opts.ConstName == "" {
		opts.ConstName = fmt.Sprintf("pcs_system_%d", index)
	}
	p := opts.ConstPrefix

	var b strings.Builder

	if opts.EmitHeader {
		fmt.Fprintln(&b, "// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.")
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "const pcs = %s;\n", opts.PcsImport)
		fmt.Fprintf(&b, "const fri = %s;\n", opts.FriImport)
		fmt.Fprintln(&b)
	}

	// Witness / quotient claim maps.
	fmt.Fprintf(&b, "const %switness_map = [_]pcs.ClaimRef{ ", p)
	pcsWriteClaimRefs(&b, system.WitnessMap)
	fmt.Fprintln(&b, " };")
	fmt.Fprintf(&b, "const %squotient_map = [_]pcs.ClaimRef{ ", p)
	pcsWriteClaimRefs(&b, system.QuotientMap)
	fmt.Fprintln(&b, " };")

	// Batch roots: each batch's transcript-bound root provenance. The Zig
	// verifier rebuilds the authenticated roots from these — reading an
	// interactive batch's root from the named round's oracle commitment and a
	// precomputed root from the emitted constant — so a batch is never
	// authenticated against a root that zeta is not bound to.
	fmt.Fprintf(&b, "const %sbatch_roots = [_]pcs.BatchRoot{ ", p)
	for i, br := range system.BatchRoots {
		if i > 0 {
			b.WriteString(", ")
		}
		if br.Precomputed {
			b.WriteString(".{ .precomputed = ")
			b.WriteString(pcsOctupletLiteral(br.Root))
			b.WriteString(" }")
		} else {
			fmt.Fprintf(&b, ".{ .round = %d }", br.RoundIndex)
		}
	}
	fmt.Fprintln(&b, " };")

	// The System literal, with the symbolic ColumnDesc list (declaration order)
	// and envelope params inline. The verifier reconstructs the canonical layout
	// from these + module_sizes.
	fmt.Fprintf(&b, "pub const %s%s = pcs.System{\n", p, opts.ConstName)
	fmt.Fprintf(&b, "    .envelope_params = fri.Params{ .log_codeword_size = %d, .log_plaintext_size = %d, .log_final_poly_size = %d, .num_queries = %d },\n",
		system.LogCodewordSize, system.LogPlaintextSize, system.LogFinalPolySize, system.NumQueries)
	fmt.Fprintf(&b, "    .columns = %s,\n", pcsColumnsLiteral(system.Columns))
	fmt.Fprintf(&b, "    .num_batches = %d,\n", system.NumBatches)
	fmt.Fprintf(&b, "    .max_entries = %d,\n", system.MaxEntries)
	fmt.Fprintf(&b, "    .max_size_log2 = %d,\n", system.MaxSizeLog2)
	fmt.Fprintf(&b, "    .witness_map = &%switness_map,\n", p)
	fmt.Fprintf(&b, "    .quotient_map = &%squotient_map,\n", p)
	fmt.Fprintf(&b, "    .batch_roots = &%sbatch_roots,\n", p)
	fmt.Fprintf(&b, "    .zeta_coin_index = %d,\n", system.ZetaCoinIndex)
	fmt.Fprintln(&b, "};")

	_, err := io.WriteString(w, b.String())
	return err
}

// pcsColumnsLiteral emits the symbolic `[]const pcs.ColumnDesc` list in prover
// declaration order: each column's batch, is_ext, size source (static size_log2
// or dynamic module_sizes index) and shift schedule.
func pcsColumnsLiteral(columns []PcsColumnDesc) string {
	var b strings.Builder
	b.WriteString("&.{ ")
	for i, c := range columns {
		if i > 0 {
			b.WriteString(", ")
		}
		var size string
		if c.IsDynamic {
			size = fmt.Sprintf(".{ .dynamic = %d }", c.DynamicIndex)
		} else {
			size = fmt.Sprintf(".{ .static = %d }", c.SizeLog2)
		}
		fmt.Fprintf(&b, ".{ .batch_idx = %d, .is_ext = %t, .size = %s, .shifts = &[_]isize%s }",
			c.BatchIdx, c.IsExt, size, pcsIntArrayLiteral(c.Shifts))
	}
	b.WriteString(" }")
	return b.String()
}

func pcsWriteClaimRefs(b *strings.Builder, refs []PcsClaimRef) {
	for i, r := range refs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, ".{ .col_decl_idx = %d, .shift = %d }", r.ColDeclIdx, r.Shift)
	}
}

// pcsIntArrayLiteral renders an int slice as a Zig array body `{ a, b, c }`
// (the shift schedule of one opened column), matching testdata/generate/fri's
// intArrayLiteral.
func pcsIntArrayLiteral(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprintf("%d", x)
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

// pcsOctupletLiteral emits a precomputed-batch root as an `[8]field.Element`
// literal `.{ .{ .value = v0 }, ... }` from the octuplet's canonical field
// values. Only the (rare) precomputed batch reaches this path; the engine's
// BatchRoot.precomputed is a poseidon2.Digest == [8]field.Element, so each limb
// must be a field.Element (a bare integer would not coerce).
func pcsOctupletLiteral(o field.Octuplet) string {
	parts := make([]string, len(o))
	for i := range o {
		parts[i] = fmt.Sprintf(".{ .value = %d }", o[i].Uint64())
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}
