#!/usr/bin/env python3
"""Generates vec_ext_mul_amd64.s: the AVX-512 element-wise product of E6
vectors. Run from maths/koalabear/field: python3 internal/gen_vec_ext_mul.py

The Montgomery product, modular addition and subtraction over 16 lanes are
those of gnark-crypto's generated koalabear extension kernels
(field/koalabear/extensions/e4_amd64.s), expanded inline.
"""

Q, QINV, IDX = "Z0", "Z1", "Z2"
A = ["Z3", "Z4", "Z5", "Z6", "Z7", "Z8"]
B = ["Z9", "Z10", "Z11", "Z12", "Z13", "Z14"]
TMP = ["Z27", "Z28", "Z29", "Z30", "Z31"]  # Montgomery product scratch
out = []


def emit(s):
    out.append("\t" + s)


def mul(x, y, dst):
    """dst = x*y*2^-32 mod q, in [0, q); dst may alias x or y."""
    t2, t3, t4, t5, t6 = TMP
    emit(f"VMOVSHDUP {x}, {t2}")
    emit(f"VMOVSHDUP {y}, {t3}")
    emit(f"VPMULUDQ  {x}, {y}, {t4}")
    emit(f"VPMULUDQ  {t2}, {t3}, {t5}")
    emit(f"VPMULUDQ  {t4}, {QINV}, {t6}")
    emit(f"VPMULUDQ  {t5}, {QINV}, {t3}")
    emit(f"VPMULUDQ  {t6}, {Q}, {t6}")
    emit(f"VPADDQ    {t4}, {t6}, {t4}")
    emit(f"VPMULUDQ  {t3}, {Q}, {t3}")
    emit(f"VPADDQ    {t5}, {t3}, {dst}")
    emit(f"VMOVSHDUP {t4}, K3, {dst}")
    # REDUCE1Q
    emit(f"VPSUBD  {Q}, {dst}, {t2}")
    emit(f"VPMINUD {dst}, {t2}, {dst}")


def add(x, y, dst):
    """dst = x+y mod q; operands in [0, q)."""
    t = TMP[0]
    emit(f"VPADDD  {y}, {x}, {dst}")
    emit(f"VPSUBD  {Q}, {dst}, {t}")
    emit(f"VPMINUD {dst}, {t}, {dst}")


def sub(x, y, dst):
    """dst = x-y mod q; operands in [0, q)."""
    t = TMP[0]
    emit(f"VPSUBD  {y}, {x}, {dst}")
    emit(f"VPADDD  {Q}, {dst}, {t}")
    emit(f"VPMINUD {dst}, {t}, {dst}")


def e2mul(xr, xi, yr, yi, re, im, s1, s2):
    """(re, im) = (xr + xi·u)(yr + yi·u), u² = 3, Karatsuba; inputs kept.
    s1, s2 are scratch."""
    mul(xr, yr, re)          # m0
    mul(xi, yi, s1)          # m1
    add(xr, xi, s2)
    add(yr, yi, im)
    mul(s2, im, im)          # m2
    sub(im, re, im)
    sub(im, s1, im)          # im = m2 - m0 - m1
    add(s1, s1, s2)
    add(s2, s1, s2)          # 3·m1
    add(re, s2, re)          # re = m0 + 3·m1


def e2mul_destroy(xr, xi, yr, yi, ta, tb):
    """Returns (re, im) registers of (xr + xi·u)(yr + yi·u); overwrites the
    inputs. ta, tb are scratch."""
    mul(xr, yr, ta)          # m0
    mul(xi, yi, tb)          # m1
    add(xr, xi, xr)
    add(yr, yi, yr)
    mul(xr, yr, xi)          # m2
    sub(xi, ta, xi)
    sub(xi, tb, xi)          # im
    add(tb, tb, yr)
    add(yr, tb, yr)          # 3·m1
    add(ta, yr, ta)          # re
    return ta, xi


def mul_xi(r, i, re, im):
    """(re, im) = ξ·(r + i·u) with ξ = 1 + u: (r + 3i) + (r + i)·u."""
    add(i, i, re)
    add(re, i, re)
    add(re, r, re)
    add(r, i, im)


def scatter(reg, limb):
    emit("KMOVD SI, K1")
    emit(f"VPSCATTERDD {reg}, K1, {4*limb}(R13)({IDX}*4)")


def body():
    for k in range(6):
        emit("KMOVD SI, K1")
        emit("KMOVD SI, K2")
        emit(f"VPGATHERDD {4*k}(R14)({IDX}*4), K1, {A[k]}")
        emit(f"VPGATHERDD {4*k}(CX)({IDX}*4), K2, {B[k]}")
    a0, a1, a2, a3, a4, a5 = A
    b0, b1, b2, b3, b4, b5 = B
    # T0 = X0·Y0, T1 = X1·Y1, T2 = X2·Y2
    e2mul(a0, a1, b0, b1, "Z15", "Z16", "Z17", "Z18")
    e2mul(a2, a3, b2, b3, "Z17", "Z18", "Z19", "Z20")
    e2mul(a4, a5, b4, b5, "Z19", "Z20", "Z21", "Z22")
    t0r, t0i, t1r, t1i, t2r, t2i = "Z15", "Z16", "Z17", "Z18", "Z19", "Z20"
    # c0 = T0 + ξ·((X1+X2)(Y1+Y2) − T1 − T2)
    add(a2, a4, "Z21"); add(a3, a5, "Z22"); add(b2, b4, "Z23"); add(b3, b5, "Z24")
    mr, mi = e2mul_destroy("Z21", "Z22", "Z23", "Z24", "Z25", "Z26")
    sub(mr, t1r, mr); sub(mr, t2r, mr)
    sub(mi, t1i, mi); sub(mi, t2i, mi)
    mul_xi(mr, mi, "Z23", "Z24")
    add(t0r, "Z23", "Z23"); add(t0i, "Z24", "Z24")
    scatter("Z23", 0); scatter("Z24", 1)
    # c1 = (X0+X1)(Y0+Y1) − T0 − T1 + ξ·T2
    add(a0, a2, "Z21"); add(a1, a3, "Z22"); add(b0, b2, "Z23"); add(b1, b3, "Z24")
    mr, mi = e2mul_destroy("Z21", "Z22", "Z23", "Z24", "Z25", "Z26")
    sub(mr, t0r, mr); sub(mr, t1r, mr)
    sub(mi, t0i, mi); sub(mi, t1i, mi)
    mul_xi(t2r, t2i, "Z23", "Z24")
    add(mr, "Z23", "Z23"); add(mi, "Z24", "Z24")
    scatter("Z23", 2); scatter("Z24", 3)
    # c2 = (X0+X2)(Y0+Y2) − T0 − T2 + T1
    add(a0, a4, "Z21"); add(a1, a5, "Z22"); add(b0, b4, "Z23"); add(b1, b5, "Z24")
    mr, mi = e2mul_destroy("Z21", "Z22", "Z23", "Z24", "Z25", "Z26")
    sub(mr, t0r, mr); sub(mr, t2r, mr); add(mr, t1r, mr)
    sub(mi, t0i, mi); sub(mi, t2i, mi); add(mi, t1i, mi)
    scatter(mr, 4); scatter(mi, 5)


body()
header = """//go:build !purego

// Code generated by internal/gen_vec_ext_mul.py. DO NOT EDIT.

#include "textflag.h"
#include "funcdata.h"
#include "go_asm.h"

// func vecMulExtAVX512(res, a, b *Ext, n uint64)
// res[i] = a[i]·b[i] for i < n, n a multiple of 16; res may alias a or b.
TEXT ·vecMulExtAVX512(SB), NOSPLIT, $0-32
	MOVD         $const_extMulQ, AX
	VPBROADCASTD AX, Z0
	MOVD         $const_extMulQInvNeg, AX
	VPBROADCASTD AX, Z1
	MOVQ         $0x0000000000005555, AX
	KMOVD        AX, K3
	MOVQ         res+0(FP), R13
	MOVQ         a+8(FP), R14
	MOVQ         b+16(FP), CX
	MOVQ         n+24(FP), BX
	MOVQ         $0xffffffffffffffff, SI
	MOVQ         ·extMulGatherIndex+0(SB), DI
	VMOVDQU32    0(DI), Z2
	SHRQ         $4, BX

loop:
	TESTQ BX, BX
	JEQ   done
	DECQ  BX
"""
footer = """	ADDQ $384, R13
	ADDQ $384, R14
	ADDQ $384, CX
	JMP  loop

done:
	RET
"""
with open("vec_ext_mul_amd64.s", "w") as f:
    f.write(header + "\n".join(out) + "\n" + footer)
