package linea.coordinator.config.v2.docs

/**
 * Generates the human-readable Markdown reference for the Coordinator config.
 *
 * Output mirrors the JSON snapshot's per-file organisation (see [COORDINATOR_CONFIG_FILES]):
 * one `##` heading per config file, a `###` heading per top-level section within it, and a table
 * of that section's leaf keys (deep, with full dotted paths). Deprecated keys are also collected
 * into a trailing "Deprecated Keys" table. The file is committed and regenerated by CI; it is not
 * meant to be edited by hand.
 */
object ConfigDocMarkdownGenerator {
  private const val BANNER =
    "<!-- Generated by ./gradlew :coordinator:app:generateCoordinatorConfigDocs. Do not edit by hand. -->"

  fun generate(files: List<CoordinatorConfigFileRoot> = COORDINATOR_CONFIG_FILES): String {
    val sb = StringBuilder()
    sb.appendLine("# Coordinator Configuration Reference")
    sb.appendLine()
    sb.appendLine(BANNER)
    sb.appendLine()

    val deprecated = mutableListOf<Pair<String, ConfigKey>>() // file label -> key

    for (file in files) {
      val keys = ConfigSchemaWalker.walk(file.rootClass)
      keys.filter { it.deprecated }.forEach { deprecated.add(file.label to it) }

      sb.appendLine("## ${file.label}")
      sb.appendLine()
      sb.appendLine(file.description)
      sb.appendLine()

      val topLevelLeaves = keys.filter { !it.path.contains(".") && !it.isSection }
      if (topLevelLeaves.isNotEmpty()) {
        appendTable(sb, topLevelLeaves)
        sb.appendLine()
      }

      val topLevelSections = keys.filter { !it.path.contains(".") && it.isSection }
      for (section in topLevelSections) {
        sb.appendLine("### `${section.path}`")
        sb.appendLine()
        if (section.description.isNotBlank()) {
          sb.appendLine(section.description)
          sb.appendLine()
        }
        val leaves = keys.filter { it.path.startsWith("${section.path}.") && !it.isSection }
        appendTable(sb, leaves)
        sb.appendLine()
      }
    }

    sb.appendLine("## Deprecated Keys")
    sb.appendLine()
    if (deprecated.isEmpty()) {
      sb.appendLine("None.")
    } else {
      sb.appendLine("| File | Key | Replacement | Description |")
      sb.appendLine("| --- | --- | --- | --- |")
      for ((label, key) in deprecated) {
        sb.appendLine(
          "| ${cell(label)} | `${key.path}` | ${key.replacement?.let { "`$it`" } ?: "-"} " +
            "| ${cell(key.description)} |",
        )
      }
    }
    sb.appendLine()
    return sb.toString()
  }

  private fun appendTable(sb: StringBuilder, leaves: List<ConfigKey>) {
    sb.appendLine("| Key | Type | Required | Default | Status | Description |")
    sb.appendLine("| --- | --- | --- | --- | --- | --- |")
    for (key in leaves) {
      sb.appendLine(
        "| `${key.path}` | `${key.type}` | ${if (key.required) "yes" else "no"} " +
          "| ${key.default?.let { "`$it`" } ?: "-"} | ${if (key.deprecated) "deprecated" else "active"} " +
          "| ${describe(key)} |",
      )
    }
  }

  private fun describe(key: ConfigKey): String {
    val example = key.example?.let { " Example: `$it`." } ?: ""
    return cell(key.description + example)
  }

  /** Escapes Markdown table cell content (pipes would otherwise break the row). */
  private fun cell(text: String): String = text.replace("|", "\\|")
}
