// Static FRI vectors captured from loom commit e58fe2fb0255.
// These are not regenerated by verifier-ray/testdata/generate because loom's
// reference FRI pieces currently live under Go internal/ packages.

pub const LoomLeafHashCase = struct { base_pairs: []const [2]u32, ext_pairs: []const [2][6]u32, expected: [8]u32 };
pub const LoomNodeHashCase = struct { left: [8]u32, right: [8]u32, expected: [8]u32 };
pub const LoomMerkleCase = struct { leaf_idx: u32, leaf: [8]u32, siblings: []const [8]u32, root: [8]u32 };
pub const LoomNamedTranscriptCase = struct { first_name: []const u8, first_bindings: []const u32, first_expected: [8]u32, second_name: []const u8, second_bindings: []const u32, second_expected: [8]u32, second_ext_expected: [6]u32 };
pub const LoomPowTranscriptCase = struct { name: []const u8, bindings: []const u32, nb_bits: u32, salt: u32, expected: [8]u32 };
pub const LoomDeepAlphaCase = struct { zeta_bindings: []const u32, zeta_digest: [8]u32, alpha_digest: [8]u32, alpha_ext: [6]u32 };
pub const LoomBridgeRail = enum { base, ext };
pub const LoomBridgeSlot = struct { name: []const u8, tree_idx: u32, poly_idx: u32, rail: LoomBridgeRail };
pub const LoomBridgeValue = struct { name: []const u8, value: [6]u32 };
pub const LoomBridgeSampling = struct {
    leaf_idx: u32,
    base_pairs: []const [2]u32 = &.{},
    ext_pairs: []const [2][6]u32 = &.{},
};
pub const LoomBridgeLayer = struct { leaf_idx: u32, leaf_p_ext: [6]u32, leaf_q_ext: [6]u32 };
pub const LoomBridgeQuery = struct {
    position: u32,
    point_samplings: []const LoomBridgeSampling,
    fri_layer: LoomBridgeLayer,
    level_layers: []const LoomBridgeLayer,
};
pub const LoomBridgeCase = struct {
    sizes: []const u32,
    tree_sizes: []const u32,
    zeta: [6]u32,
    alpha: [6]u32,
    eval_points: []const []const [6]u32,
    column_names: []const []const []const []const u8,
    column_keys: []const []const []const []const u8,
    air_chunks: []const []const []const u8,
    values_at_zeta: []const LoomBridgeValue,
    col_slots: []const LoomBridgeSlot,
    air_chunk_slots: []const LoomBridgeSlot,
    queries: []const LoomBridgeQuery,
};

pub const loom_leaf_hash_cases = [_]LoomLeafHashCase{
    .{ .base_pairs = &.{ .{ 1, 2 }, .{ 3, 4 } }, .ext_pairs = &.{}, .expected = .{ 175048833, 176667958, 412629434, 70021978, 663448090, 765878282, 380110844, 1591199718 } },
    .{ .base_pairs = &.{}, .ext_pairs = &.{.{ .{ 5, 6, 7, 8, 9, 10 }, .{ 10, 9, 8, 7, 6, 5 } }}, .expected = .{ 2007204097, 1796522763, 1520713598, 95691836, 712885359, 1064890402, 827077939, 1331345999 } },
    .{ .base_pairs = &.{.{ 11, 12 }}, .ext_pairs = &.{ .{ .{ 13, 14, 15, 16, 17, 18 }, .{ 18, 17, 16, 15, 14, 13 } }, .{ .{ 19, 20, 21, 22, 23, 24 }, .{ 24, 23, 22, 21, 20, 19 } } }, .expected = .{ 1912478430, 2119645984, 1225534222, 1143553878, 1574346462, 900469027, 1860313766, 1375628729 } },
};

pub const loom_node_hash_cases = [_]LoomNodeHashCase{
    .{ .left = .{ 0, 1, 2, 3, 4, 5, 6, 7 }, .right = .{ 8, 9, 10, 11, 12, 13, 14, 15 }, .expected = .{ 993811729, 1346705934, 1780910111, 1620995220, 1122135399, 2103616599, 1523292476, 412125550 } },
    .{ .left = .{ 2130706432, 2130706431, 17, 19, 23, 29, 31, 37 }, .right = .{ 41, 43, 47, 53, 59, 61, 67, 71 }, .expected = .{ 1065466939, 1713958770, 1060196385, 500138362, 760688506, 846896138, 1379446464, 1572245111 } },
};

pub const loom_merkle_cases = [_]LoomMerkleCase{
    .{ .leaf_idx = 2, .leaf = .{ 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368 }, .siblings = &.{ .{ 17, 31, 47, 71, 97, 127, 191, 255 }, .{ 489790638, 2075422165, 167955246, 1682428282, 1804484632, 1652252653, 1142574511, 1009285235 } }, .root = .{ 1483493281, 1144009809, 1561904753, 2097440507, 1575690085, 621769059, 1911106415, 131523661 } },
};

pub const loom_named_transcript_cases = [_]LoomNamedTranscriptCase{
    .{ .first_name = "alpha_DEEP", .first_bindings = &.{ 1, 2, 3 }, .first_expected = .{ 237970668, 1712327120, 584884788, 1448816272, 723608600, 1528613085, 1258900048, 1371512671 }, .second_name = "fri_query_0", .second_bindings = &.{ 5, 8 }, .second_expected = .{ 1474751485, 1414964790, 1341537908, 2127095122, 378471079, 1528571225, 507926663, 277830736 }, .second_ext_expected = .{ 1474751485, 1414964790, 1341537908, 2127095122, 378471079, 1528571225 } },
};

pub const loom_pow_transcript_cases = [_]LoomPowTranscriptCase{
    .{ .name = "fri_fold_0", .bindings = &.{ 13, 21, 34 }, .nb_bits = 4, .salt = 2, .expected = .{ 1036995264, 1561072429, 614459829, 1073122740, 598664813, 1873880090, 1102096053, 1822996418 } },
};

pub const loom_deep_alpha_cases = [_]LoomDeepAlphaCase{
    .{
        .zeta_bindings = &.{ 3, 1, 4, 1 },
        .zeta_digest = .{ 1917250265, 622384269, 2073146317, 1819043742, 640412108, 317252013, 1545741056, 225608101 },
        .alpha_digest = .{ 191465002, 725753667, 911742404, 395965214, 1392090261, 2116157538, 1642781672, 411925872 },
        .alpha_ext = .{ 191465002, 725753667, 911742404, 395965214, 1392090261, 2116157538 },
    },
};

pub const loom_bridge_cases = [_]LoomBridgeCase{
    .{
        .sizes = &.{ 4, 2 },
        .tree_sizes = &.{ 4, 4, 2, 4, 2 },
        .zeta = .{ 2, 3, 5, 7, 11, 13 },
        .alpha = .{ 17, 19, 23, 29, 31, 37 },
        .eval_points = &.{
            &.{
                .{ 2, 3, 5, 7, 11, 13 },
                .{ 2097283075, 2080571396, 2047148038, 2013724680, 1946877964, 1913454606 },
            },
            &.{
                .{ 2, 3, 5, 7, 11, 13 },
            },
        },
        .column_names = &.{
            &.{ &.{ "base_col", "ext_col" }, &.{"shifted"} },
            &.{&.{"small_col"}},
        },
        .column_keys = &.{
            &.{ &.{ "base_col", "ext_col" }, &.{"shifted@1"} },
            &.{&.{"small_col"}},
        },
        .air_chunks = &.{
            &.{"air0"},
            &.{"air1"},
        },
        .values_at_zeta = &.{
            .{ .name = "base_col", .value = .{ 41, 43, 47, 53, 59, 61 } },
            .{ .name = "ext_col", .value = .{ 67, 71, 73, 79, 83, 89 } },
            .{ .name = "shifted@1", .value = .{ 97, 101, 103, 107, 109, 113 } },
            .{ .name = "air0", .value = .{ 127, 131, 137, 139, 149, 151 } },
            .{ .name = "small_col", .value = .{ 157, 163, 167, 173, 179, 181 } },
            .{ .name = "air1", .value = .{ 191, 193, 197, 199, 211, 223 } },
        },
        .col_slots = &.{
            .{ .name = "base_col", .tree_idx = 0, .poly_idx = 0, .rail = .base },
            .{ .name = "ext_col", .tree_idx = 0, .poly_idx = 0, .rail = .ext },
            .{ .name = "shifted", .tree_idx = 1, .poly_idx = 0, .rail = .base },
            .{ .name = "small_col", .tree_idx = 2, .poly_idx = 0, .rail = .base },
        },
        .air_chunk_slots = &.{
            .{ .name = "air0", .tree_idx = 3, .poly_idx = 0, .rail = .ext },
            .{ .name = "air1", .tree_idx = 4, .poly_idx = 0, .rail = .base },
        },
        .queries = &.{
            .{
                .position = 5,
                .point_samplings = &.{
                    .{
                        .leaf_idx = 5,
                        .base_pairs = &.{.{ 101, 202 }},
                        .ext_pairs = &.{.{ .{ 11, 12, 13, 14, 15, 16 }, .{ 21, 22, 23, 24, 25, 26 } }},
                    },
                    .{ .leaf_idx = 5, .base_pairs = &.{.{ 303, 404 }} },
                    .{ .leaf_idx = 1, .base_pairs = &.{.{ 505, 606 }} },
                    .{ .leaf_idx = 5, .ext_pairs = &.{.{ .{ 31, 32, 33, 34, 35, 36 }, .{ 41, 42, 43, 44, 45, 46 } }} },
                    .{ .leaf_idx = 1, .base_pairs = &.{.{ 707, 808 }} },
                },
                .fri_layer = .{
                    .leaf_idx = 5,
                    .leaf_p_ext = .{ 325972778, 89126247, 1091765009, 1755692889, 1446411246, 1532764431 },
                    .leaf_q_ext = .{ 1138542604, 801229393, 1951056852, 1557597112, 976467535, 239151014 },
                },
                .level_layers = &.{
                    .{
                        .leaf_idx = 1,
                        .leaf_p_ext = .{ 2051499819, 263238869, 1427227396, 1583866796, 908593113, 1094507607 },
                        .leaf_q_ext = .{ 1716779178, 1070011699, 403459898, 194414717, 242072824, 1574832895 },
                    },
                },
            },
            .{
                .position = 2,
                .point_samplings = &.{
                    .{
                        .leaf_idx = 2,
                        .base_pairs = &.{.{ 909, 1001 }},
                        .ext_pairs = &.{.{ .{ 51, 52, 53, 54, 55, 56 }, .{ 61, 62, 63, 64, 65, 66 } }},
                    },
                    .{ .leaf_idx = 2, .base_pairs = &.{.{ 1102, 1203 }} },
                    .{ .leaf_idx = 2, .base_pairs = &.{.{ 1304, 1405 }} },
                    .{ .leaf_idx = 2, .ext_pairs = &.{.{ .{ 71, 72, 73, 74, 75, 76 }, .{ 81, 82, 83, 84, 85, 86 } }} },
                    .{ .leaf_idx = 2, .base_pairs = &.{.{ 1506, 1607 }} },
                },
                .fri_layer = .{
                    .leaf_idx = 2,
                    .leaf_p_ext = .{ 924713015, 487900529, 633930907, 643417939, 163334203, 2103493026 },
                    .leaf_q_ext = .{ 1622673338, 951716292, 615474912, 123882709, 696786084, 1048087535 },
                },
                .level_layers = &.{
                    .{
                        .leaf_idx = 2,
                        .leaf_p_ext = .{ 670407641, 308097103, 764665664, 1380042554, 1474896185, 1112829785 },
                        .leaf_q_ext = .{ 1953161431, 830377977, 1199145495, 470465009, 46326097, 645461657 },
                    },
                },
            },
        },
    },
};
