---
name: 'assemble'
description: 'Composite action to assemble the artifacts for the target environment'

inputs:
  local_besu_version:
    description: 'Besu version defined in gradle/libs.versions.toml'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set local zip paths
      id: set_local_zip_paths
      shell: bash
      run: |
        echo "local_tracer_dist_path=$GITHUB_WORKSPACE/tracer/plugins/build/install/linea-tracer" >> $GITHUB_OUTPUT
        echo "local_sequencer_dist_path=$GITHUB_WORKSPACE/linea-besu/plugins/linea-sequencer/sequencer/build/install/sequencer" >> $GITHUB_OUTPUT
        echo "local_besu_zip_path=$GITHUB_WORKSPACE/tmp/besu-eth/build/distributions/besu-${{ inputs.local_besu_version }}.tar.gz" >> $GITHUB_OUTPUT

    - name: assemble the packages to linea-besu
      shell: bash
      env:
        LOCAL_BESU_VERSION: ${{ inputs.local_besu_version }}
        LOCAL_TRACER_DIST_PATH: ${{ steps.set_local_zip_paths.outputs.local_tracer_dist_path }}
        LOCAL_SEQUENCER_DIST_PATH: ${{ steps.set_local_zip_paths.outputs.local_sequencer_dist_path }}
        LOCAL_BESU_ZIP_PATH: ${{ steps.set_local_zip_paths.outputs.local_besu_zip_path }}
      run: |
        cd linea-besu/package
        BESU_VERSION="$LOCAL_BESU_VERSION" LOCAL_BESU_ZIP_PATH="$LOCAL_BESU_ZIP_PATH" LOCAL_TRACER_DIST_FOLDER="$LOCAL_TRACER_DIST_PATH" LOCAL_SEQUENCER_DIST_FOLDER="$LOCAL_SEQUENCER_DIST_PATH" make assemble
        mv ./tmp/besu ./linea-besu
    
    - name: show folder structure
      shell: bash
      run: |
        cd linea-besu/package
        sudo apt update
        sudo apt-get install --no-install-recommends --assume-yes tree
        tree .

