[protocol.l1]
contract-address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[conflation]
blocks-limit = 1
riscv-starting-block-timestamp-inclusive = 0

[conflation.proof-aggregation]
timestamp-based-hard-forks = [0]

[riscv-prover]
fs-polling-interval = "PT1S"
fs-polling-timeout = "PT10M"
enable-request-files-cleanup = false

[riscv-prover.execution]
fs-requests-directory = "/data/prover/riscv/execution/requests"
fs-responses-directory = "/data/prover/riscv/execution/responses"
program-vk = "0x17d2e0660946012c80c5fe6bbecc2076a6f6f5aa58606efe66a14426d2ffe46f"
fork-name = "Osaka"

[riscv-prover.rollup]
fs-requests-directory = "/data/prover/riscv/rollup/requests"
fs-responses-directory = "/data/prover/riscv/rollup/responses"
program-vk = "0x0000000000000000000000000000000000000000000000000000000000000000"

[riscv-prover.proof-aggregation]
fs-requests-directory = "/data/prover/riscv/aggregation/requests"
fs-responses-directory = "/data/prover/riscv/aggregation/responses"
program-vk = "0x0000000000000000000000000000000000000000000000000000000000000000"

[traces.counters]
endpoints = ["http://sequencer:8545/"]

[traces.conflation]
endpoints = ["http://sequencer:8545/"]

[type2-state-proof-provider]
disabled = true

[l1-submission.blob]
disabled = true

[l1-submission.blob.signer]
type = "Web3j"

[l1-submission.aggregation]
disabled = true

[l1-submission.aggregation.signer]
type = "Web3j"

[message-anchoring]
disabled = true

[message-anchoring.signer]
type = "Web3j"

[forced-transactions]
disabled = true

[l2-network-gas-pricing]
disabled = true
