// Coexisting vanishing + FRI/PCS fixture generator.
//
// Builds ONE wiop.System that carries both a global (vanishing) constraint and
// a FRI/PCS commitment, proves it, and serializes everything the verifier-ray
// top-level `verifier.verify` needs to run BOTH sub-verifiers against a single
// shared transcript:
//
//   - the vanishing System (via codegen.BuildVanishingSystem),
//   - the PCS System (params + shapes + shifts → layout in Zig),
//   - the claim maps that route each vanishing witness/quotient claim to its
//     PCS-authenticated entry_claims slot (the whole point: prove the two
//     sub-verifiers consume the SAME values),
//   - the zeta coin index, the batch roots, the OpeningProof, and the full
//     transcript rounds (so replayWithTranscript reproduces the FS state the
//     FRI opener continues from).
//
// This is the empirical demonstration that witness_claims/quotient_claims ARE a
// re-slicing of entry_claims: the Zig test flips one entry_claims value and the
// vanishing check (not just PCS) rejects it.
//
// Regenerate with: cd testdata/generate && go run . -coexist
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	fri "github.com/LFDT-Lineth/lineth-monorepo/prover-ray/crypto/koalabear/fri"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/maths/koalabear/field"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/global"
	pcscompiler "github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/pcs"
	"github.com/consensys/linea-monorepo/verifier-ray/codegen"
)

// friLogInverseRate mirrors the (unexported) pcs compiler constant; the codeword
// domain is 2^friLogInverseRate × the padded plaintext size.
const friLogInverseRate = 1

// buildCoexistSystem is the minimal protocol that exercises BOTH sub-verifiers:
// one size-4 committed oracle column with a single global vanishing constraint
// L_1·(col − 99) = 0 over it. global.Compile turns the witness/quotient claims
// into LagrangeEvals evaluated at its eval coin (zeta); pcs.Compile commits the
// columns and opens those claims. Returns the system and the witness column so
// the caller can assign it. The constraint holds iff col[1] == 99.
func buildCoexistSystem() (*wiop.System, *wiop.Column) {
	sys := wiop.NewSystemf("coexist")
	r0 := sys.NewRound()
	mod := sys.NewSizedModule(sys.Context.Childf("mod"), 4, wiop.PaddingDirectionNone)
	col := mod.NewColumn(sys.Context.Childf("col"), wiop.VisibilityOracle, r0)
	selector := wiop.NewLagrangeSelector(mod, 1)
	value := wiop.NewConstantField(elem(99))
	mod.NewVanishing(sys.Context.Childf("boundary"), wiop.Mul(selector, wiop.Sub(col.View(), value)))
	return sys, col
}

// ── emit ──────────────────────────────────────────────────────────────────────

func emitCoexist(out *bytes.Buffer, fx coexistFixture) {
	fmt.Fprintln(out, "// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.")
	fmt.Fprintln(out, "//")
	fmt.Fprintln(out, "// A REAL protocol carrying BOTH a global vanishing constraint AND a FRI/PCS")
	fmt.Fprintln(out, "// commitment, produced by prover-ray. The verifier-ray end-to-end test runs the")
	fmt.Fprintln(out, "// full verifier.verify: PCS authenticates entry_claims, then the vanishing check")
	fmt.Fprintln(out, "// consumes those SAME values re-sliced via the claim maps. Every value is from")
	fmt.Fprintln(out, "// the Go prover; regenerate with: cd testdata/generate && go run . -coexist")
	fmt.Fprintln(out)
	fmt.Fprintln(out, `const verifier_ray = @import("verifier_ray");`)
	fmt.Fprintln(out, "const field = verifier_ray.field.koalabear;")
	fmt.Fprintln(out, "const ext = verifier_ray.field.koalabear_ext;")
	fmt.Fprintln(out, "const protocol = verifier_ray.protocol;")
	fmt.Fprintln(out, "const verifier = verifier_ray.verifier;")
	fmt.Fprintln(out, "const vanishing = verifier_ray.query.vanishing;")
	fmt.Fprintln(out, "const logderivativesum = verifier_ray.query.logderivativesum;")
	fmt.Fprintln(out, "const pcs = verifier_ray.pcs.root;")
	fmt.Fprintln(out, "const layout = pcs.layout;")
	fmt.Fprintln(out, "const pcsverify = pcs.verify;")
	fmt.Fprintln(out, "const tree = pcs.tree;")
	fmt.Fprintln(out, "const pl = pcs.paired_leaf;")
	fmt.Fprintln(out)

	emitCoexistBody(out, fx)
}

// emitCoexistBody emits everything except the file header/imports: the spec,
// vanishing System, PCS System, inputs, opening proof, and transcript rounds.
// It uses fixed top-level const names (spec, system_0, pcs_system, params,
// roots, proof, …), so callers that emit multiple fixtures in one file must
// wrap each emitCoexistBody in its own namespace (a `const X = struct { … };`)
// to avoid name collisions — see writeVerifyCase.
func emitCoexistBody(out *bytes.Buffer, fx coexistFixture) {
	emitCoexistSpec(out, fx.routing)
	emitCoexistVanishing(out, fx.van)
	emitCoexistLogDeriv(out, fx)
	emitCoexistPcsSystem(out, fx)
	emitCoexistInputs(out, fx)
	emitCoexistProof(out, fx.proof)
	emitCoexistRounds(out, fx.rounds)
}

// emitCoexistLogDeriv writes the logderivativesum.System (as `system_0_logderiv`)
// for fixtures that carry log-derivative queries; skipped otherwise.
func emitCoexistLogDeriv(out *bytes.Buffer, fx coexistFixture) {
	if !fx.hasLogDeriv {
		return
	}
	if err := codegen.WriteLogDerivSystemZigWithOptions(out, 0, fx.logDeriv, codegen.LogDerivZigOptions{
		LogDerivImport: "logderivativesum",
		EmitImport:     false,
	}); err != nil {
		panic(err)
	}
	fmt.Fprintln(out)
}

// emitCoexistSpec writes the protocol.Spec from the coin routing.
func emitCoexistSpec(out *bytes.Buffer, r codegen.CoinRouting) {
	fmt.Fprintf(out, "pub const spec = protocol.Spec{ .round_coin_counts = &.{ %s }, .round_coin_offsets = &.{ %s }, .total_round_coins = %d };\n\n",
		intListInts(r.RoundCoinCounts), intListInts(r.RoundCoinOffsets), r.TotalRoundCoins)
}

// emitCoexistVanishing writes the vanishing.System via codegen (no header/list).
func emitCoexistVanishing(out *bytes.Buffer, van codegen.VanishingSystem) {
	opts := codegen.VanishingZigOptions{
		FieldImport:     "field",
		VanishingImport: "vanishing",
		EmitHeader:      false,
		EmitSystemsList: false,
	}
	if err := codegen.WriteVanishingSystemZigWithOptions(out, 0, van, opts); err != nil {
		panic(err)
	}
	fmt.Fprintln(out)
}

// emitCoexistPcsSystem writes params, shapes, shifts, the PCS verify.System
// (with claim maps + zeta index), and the combined verifier.Systems.
func emitCoexistPcsSystem(out *bytes.Buffer, fx coexistFixture) {
	fmt.Fprintf(out, "pub const params = pcs.Params{ .log_codeword_size = %d, .log_plaintext_size = %d, .num_queries = %d, .log_final_poly_size = %d };\n\n",
		fx.logCodeword, fx.logPlain, fx.numQueries, bitsLen(len(fx.proof.FRIProof.FinalPoly)))

	// Shapes: one Shape per batch.
	for bi, shape := range fx.shapes {
		fmt.Fprintf(out, "const batch%d_shape = [_]layout.SizedShape{\n", bi)
		for _, s := range shape {
			fmt.Fprintf(out, "    .{ .base_width = %d, .ext_width = %d },\n", s.BaseWidth, s.ExtWidth)
		}
		fmt.Fprintln(out, "};")
	}
	fmt.Fprint(out, "pub const shapes = [_]layout.Shape{ ")
	for bi := range fx.shapes {
		if bi > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&batch%d_shape", bi)
	}
	fmt.Fprintln(out, " };")

	// Shifts.
	for bi, bs := range fx.shifts {
		for sizeLog2, ss := range bs {
			for r, row := range ss.Base {
				fmt.Fprintf(out, "const b%d_s%d_base_%d = [_]usize{ %s };\n", bi, sizeLog2, r, intListInts(row))
			}
			for r, row := range ss.Ext {
				fmt.Fprintf(out, "const b%d_s%d_ext_%d = [_]usize{ %s };\n", bi, sizeLog2, r, intListInts(row))
			}
		}
		fmt.Fprintf(out, "const batch%d_shifts = [_]layout.SizedShifts{\n", bi)
		for sizeLog2, ss := range bs {
			fmt.Fprint(out, "    .{ .base = &.{")
			for r := range ss.Base {
				if r > 0 {
					fmt.Fprint(out, ",")
				}
				fmt.Fprintf(out, " &b%d_s%d_base_%d", bi, sizeLog2, r)
			}
			fmt.Fprint(out, " }, .ext = &.{")
			for r := range ss.Ext {
				if r > 0 {
					fmt.Fprint(out, ",")
				}
				fmt.Fprintf(out, " &b%d_s%d_ext_%d", bi, sizeLog2, r)
			}
			fmt.Fprintln(out, " } },")
		}
		fmt.Fprintln(out, "};")
	}
	fmt.Fprint(out, "pub const shifts = [_]layout.BatchShifts{ ")
	for bi := range fx.shifts {
		if bi > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&batch%d_shifts", bi)
	}
	fmt.Fprintln(out, " };")

	// Claim maps.
	fmt.Fprint(out, "const witness_map = [_]pcsverify.ClaimRef{ ")
	emitClaimRefs(out, fx.witnessMap)
	fmt.Fprintln(out, " };")
	fmt.Fprint(out, "const quotient_map = [_]pcsverify.ClaimRef{ ")
	emitClaimRefs(out, fx.quotientMap)
	fmt.Fprintln(out, " };")

	fmt.Fprintln(out, "pub const pcs_system = pcsverify.System{")
	fmt.Fprintln(out, "    .params = params,")
	fmt.Fprintln(out, "    .layout = layout.buildLayout(&shapes, &shifts) catch unreachable,")
	fmt.Fprintln(out, "    .shapes = &shapes,")
	fmt.Fprintf(out, "    .num_batches = %d,\n", len(fx.shapes))
	fmt.Fprintln(out, "    .witness_map = &witness_map,")
	fmt.Fprintln(out, "    .quotient_map = &quotient_map,")
	fmt.Fprintf(out, "    .zeta_coin_index = %d,\n", fx.zetaCoinIdx)
	fmt.Fprintln(out, "};")

	// Combined systems. The vanishing System codegen emits `system_0`; logderiv
	// (system_0_logderiv) is included only when the fixture has queries.
	if fx.hasLogDeriv {
		fmt.Fprintln(out, "pub const systems = verifier.Systems{ .vanishing = system_0, .logderivativesum = system_0_logderiv, .pcs = pcs_system };")
	} else {
		fmt.Fprintln(out, "pub const systems = verifier.Systems{ .vanishing = system_0, .pcs = pcs_system };")
	}
	fmt.Fprintln(out)
}

func emitClaimRefs(out *bytes.Buffer, refs []claimRef) {
	for i, r := range refs {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, ".{ .entry = %d, .shift = %d }", r.entry, r.shift)
	}
}

// emitCoexistInputs writes roots and entry_claims (flat canonical order).
func emitCoexistInputs(out *bytes.Buffer, fx coexistFixture) {
	fmt.Fprint(out, "pub const roots = [_]tree.Octuplet{ ")
	for i, r := range fx.roots {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitOctuplet(out, r)
	}
	fmt.Fprintln(out, " };")

	for g, col := range fx.entryClaims {
		fmt.Fprintf(out, "const entry_col_%d = [_]ext.Ext{ ", g)
		for j, v := range col {
			if j > 0 {
				fmt.Fprint(out, ", ")
			}
			emitExt(out, v)
		}
		fmt.Fprintln(out, " };")
	}
	fmt.Fprint(out, "pub const entry_claims = [_][]const ext.Ext{ ")
	for g := range fx.entryClaims {
		if g > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&entry_col_%d", g)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out)
}

// emitCoexistProof reuses the frip proof serialization shape.
func emitCoexistProof(out *bytes.Buffer, proof *fri.OpeningProof) {
	fmt.Fprint(out, "pub const round_roots = [_]tree.Octuplet{ ")
	for i, r := range proof.FRIProof.RoundRoots {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitOctuplet(out, r)
	}
	fmt.Fprintln(out, " };")

	fmt.Fprint(out, "pub const final_poly = [_]ext.Ext{ ")
	for i, c := range proof.FRIProof.FinalPoly {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitExt(out, c)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out)

	for q, iq := range proof.InputQueries {
		for b, opening := range iq {
			emitInputTreeOpening(out, q, b, opening)
		}
	}
	fmt.Fprintln(out, "pub const input_queries = assembleInputQueries();")
	fmt.Fprintln(out, "fn assembleInputQueries() []const []const pl.InputTreeOpening {")
	fmt.Fprintln(out, "    const S = struct {")
	for q := range proof.InputQueries {
		fmt.Fprintf(out, "        const q%d = [_]pl.InputTreeOpening{ ", q)
		for b := range proof.InputQueries[q] {
			if b > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, "iq_%d_%d", q, b)
		}
		fmt.Fprintln(out, " };")
	}
	fmt.Fprint(out, "        const all = [_][]const pl.InputTreeOpening{ ")
	for q := range proof.InputQueries {
		if q > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&q%d", q)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "    return &S.all;")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)

	for q, rq := range proof.FRIProof.RunningQueries {
		for layerIdx, layer := range rq {
			emitBranch(out, q, layerIdx, layer[0])
		}
	}
	fmt.Fprintln(out, "pub const running_queries = assembleRunningQueries();")
	fmt.Fprintln(out, "fn assembleRunningQueries() []const []const tree.Branch {")
	fmt.Fprintln(out, "    const S = struct {")
	for q, rq := range proof.FRIProof.RunningQueries {
		fmt.Fprintf(out, "        const q%d = [_]tree.Branch{ ", q)
		for layerIdx := range rq {
			if layerIdx > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, "rq_%d_%d", q, layerIdx)
		}
		fmt.Fprintln(out, " };")
	}
	fmt.Fprint(out, "        const all = [_][]const tree.Branch{ ")
	for q := range proof.FRIProof.RunningQueries {
		if q > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&q%d", q)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "    return &S.all;")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

// emitCoexistRounds writes the transcript rounds as protocol.RoundMessage.
func emitCoexistRounds(out *bytes.Buffer, rounds []coexistRound) {
	for i, r := range rounds {
		if r.commitment != nil {
			fmt.Fprintf(out, "const round%d_cols = [_]protocol.ColumnMessage{ .{ .oracle_commitment = ", i)
			emitOctuplet(out, *r.commitment)
			fmt.Fprintln(out, " } };")
		}
		if len(r.cells) > 0 {
			fmt.Fprintf(out, "const round%d_cells = [_]protocol.Scalar{ ", i)
			for j, c := range r.cells {
				if j > 0 {
					fmt.Fprint(out, ", ")
				}
				if c.base != nil {
					fmt.Fprintf(out, ".{ .base = field.Element.init(%d) }", elemVal(*c.base))
				} else {
					fmt.Fprint(out, ".{ .ext = ")
					emitExt(out, *c.ext)
					fmt.Fprint(out, " }")
				}
			}
			fmt.Fprintln(out, " };")
		}
	}
	fmt.Fprint(out, "pub const rounds = [_]protocol.RoundMessage{\n")
	for i, r := range rounds {
		fmt.Fprint(out, "    .{")
		if r.commitment != nil {
			fmt.Fprintf(out, " .columns = &round%d_cols,", i)
		}
		if len(r.cells) > 0 {
			fmt.Fprintf(out, " .cells = &round%d_cells,", i)
		}
		fmt.Fprintln(out, " },")
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	// The assembled verifier.Proof + PcsClaims for the test to consume.
	fmt.Fprintln(out, "pub const proof = verifier.Proof{")
	fmt.Fprintln(out, "    .rounds = &rounds,")
	fmt.Fprintln(out, "    .claims = .{")
	fmt.Fprintln(out, "        .inputs = .{ .roots = &roots, .entry_claims = &entry_claims, .zeta = ext.Ext.zero() },")
	fmt.Fprintln(out, "        .proof = .{ .input_queries = input_queries, .fri = .{ .round_roots = &round_roots, .final_poly = &final_poly, .running_queries = running_queries } },")
	fmt.Fprintln(out, "    },")
	fmt.Fprintln(out, "};")
}

// intListInts renders a Go []int as a comma-separated Zig list.
func intListInts(xs []int) string {
	var b bytes.Buffer
	for i, x := range xs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%d", x)
	}
	return b.String()
}

// ── batch enumeration ─────────────────────────────────────────────────────────
//
// The canonical batch ordering and per-batch layout come straight from the
// prover-ray PCS compiler's exported helpers ([pcscompiler.CommittedBatches] /
// [pcscompiler.GetLayout]), so this generator can never drift from the prover's
// committed-column ordering. `pcscompiler.ColumnLocation` carries the
// (SizeID, Position, IsExt) coordinates within a batch.

// locWithBatchT is a column location plus the batch index it belongs to.
type locWithBatchT struct {
	batchIdx int
	loc      pcscompiler.ColumnLocation
}

// ── serialization entry point ─────────────────────────────────────────────────

func writeCoexistFixture() error {
	fx := buildCoexistFixture()
	var out bytes.Buffer
	emitCoexist(&out, fx)
	data := out.Bytes()
	if formatted, err := runZigFmt(data); err == nil {
		data = formatted
	}
	return os.WriteFile(filepath.Join("..", "generated", "coexist.zig"), data, 0o644)
}

// ── fixture assembly ──────────────────────────────────────────────────────────

// entryKey identifies one opened column in the flat canonical entry order.
type entryKey struct {
	batchIdx int
	sizeLog2 int
	isExt    bool
	position int
}

// claimRef is the (flat entry index, shift slot) an opened (column, shift) maps
// to — the verifier-ray verify.ClaimRef.
type claimRef struct {
	entry int
	shift int
}

// claimCellKey keys a claimed evaluation by its opened column (entryKey) and
// normalized shift.
type claimCellKey struct {
	key   entryKey
	shift int
}

type coexistFixture struct {
	sys     *wiop.System
	rt      *wiop.Runtime
	routing codegen.CoinRouting
	van     codegen.VanishingSystem
	// logDeriv is emitted only for fixtures that carry a logderivativesum query
	// (hasLogDeriv true). The minimal coexist toy has none, so it is skipped and
	// verifier.Systems.logderivativesum keeps its `.{}` default.
	logDeriv    codegen.LogDerivSystem
	hasLogDeriv bool

	// PCS System pieces.
	logCodeword int
	logPlain    int
	numQueries  int
	shapes      []fri.Shape // per batch
	shifts      []fri.BatchShifts

	roots       []field.Octuplet
	entryClaims [][]field.Ext // flat canonical order; inner = per shift
	zetaCoinIdx int

	witnessMap  []claimRef
	quotientMap []claimRef

	proof *fri.OpeningProof

	// Transcript rounds in verifier-ray RoundMessage shape.
	rounds []coexistRound
}

// coexistRound is one verifier-ray RoundMessage: either a committed root (for
// HasCommitment rounds) and/or public columns, plus cell scalars.
type coexistRound struct {
	commitment *field.Octuplet // oracle_commitment, if the round has one
	cells      []coexistCell
}

type coexistCell struct {
	base *field.Element
	ext  *field.Ext
}

func buildCoexistFixture() coexistFixture {
	pcscompiler.SetFRINumQueriesForTest(1)
	sys, col := buildCoexistSystem()
	global.Compile(sys)
	pcscompiler.Compile(sys)

	rt := runProver(sys, func(rt *wiop.Runtime) {
		rt.AssignColumn(col, concreteBase(elems(7, 99, 7, 7)))
	})

	return extractPcsFixture(sys, rt)
}

// extractPcsFixture builds a PCS-enabled fixture from an ALREADY compiled
// (global.Compile + pcs.Compile) and proven (sys, rt). Everything here is
// generic over the protocol — it reads only the committed batches, the
// LagrangeEval openings, the coin routing, and the runtime's opening proof — so
// main.go can call it on a real scenario's system, not just the coexist toy.
func extractPcsFixture(sys *wiop.System, rt *wiop.Runtime) coexistFixture {
	routing, err := codegen.BuildCoinRouting(sys)
	if err != nil {
		panic(err)
	}
	van, err := codegen.BuildVanishingSystem(sys, routing)
	if err != nil {
		panic(err)
	}
	logDeriv, err := codegen.BuildLogDerivSystem(sys)
	if err != nil {
		panic(err)
	}

	batches := pcscompiler.CommittedBatches(sys)

	// Per-batch layout + shapes, and a global column->location map (with batch).
	colLoc := map[wiop.ObjectID]locWithBatchT{}
	shapes := make([]fri.Shape, len(batches))
	roots := make([]field.Octuplet, len(batches))
	for i, b := range batches {
		locs, shape := pcscompiler.GetLayout(b.Round, rt)
		shapes[i] = shape
		for id, l := range locs {
			colLoc[id] = locWithBatchT{batchIdx: i, loc: l}
		}
		// Roots: precomputed batch from the system, interactive batches from the
		// runtime's per-round commitments (keyed by round ID).
		if b.IsPrecomp {
			roots[i] = sys.PrecomputedCommitment
			continue
		}
		root, ok := rt.Commitments[b.Round.ID]
		if !ok {
			panic(fmt.Sprintf("coexist: no commitment for round %d", b.Round.ID))
		}
		roots[i] = root
	}

	// Shifts: for each opened (column, shift), record shift into the batch's
	// per-size shift schedule, keyed to the column's row. Also collect the
	// claimed value per (entry, shift) for entry_claims and the claim maps.
	shifts := make([]fri.BatchShifts, len(batches))
	for i := range batches {
		shifts[i] = initCoexistShifts(shapes[i])
	}
	// claimValues[(key,shift)] = claimed evaluation; shiftOrder[key] = ordered shifts.
	claimValues := map[claimCellKey]field.Ext{}
	shiftOrder := map[entryKey][]int{}

	recordClaim := func(cv *wiop.ColumnView, value field.Ext) entryKey {
		lb, ok := colLoc[cv.Column.Context.ID]
		if !ok {
			panic(fmt.Sprintf("coexist: opened column %v not in any committed batch", cv.Column.Context.ID))
		}
		size := 1 << lb.loc.SizeID
		shift := ((cv.ShiftingOffset % size) + size) % size
		key := entryKey{batchIdx: lb.batchIdx, sizeLog2: lb.loc.SizeID, isExt: lb.loc.IsExt, position: lb.loc.Position}
		if _, seen := claimValues[claimCellKey{key, shift}]; !seen {
			shiftOrder[key] = append(shiftOrder[key], shift)
			claimValues[claimCellKey{key, shift}] = value
			// Register into the batch's fri shift schedule.
			ss := &shifts[key.batchIdx][key.sizeLog2]
			if key.isExt {
				ss.Ext[key.position] = append(ss.Ext[key.position], shift)
			} else {
				ss.Base[key.position] = append(ss.Base[key.position], shift)
			}
		}
		return key
	}

	for _, le := range sys.LagrangeEvals {
		for k, cv := range le.Polynomials {
			value := rt.GetCellValue(le.EvaluationClaims[k]).AsExt()
			recordClaim(cv, value)
		}
	}

	// Flat canonical entry order: size DESC, batch ASC, base-then-ext, position
	// ASC. Build entry index for each key + the per-entry claim values.
	maxSize := 0
	for _, sh := range shapes {
		if len(sh)-1 > maxSize {
			maxSize = len(sh) - 1
		}
	}
	entryIndex := map[entryKey]int{}
	var entryClaims [][]field.Ext
	g := 0
	for sizeLog2 := maxSize; sizeLog2 >= 0; sizeLog2-- {
		for bi := range batches {
			if sizeLog2 >= len(shapes[bi]) {
				continue
			}
			sh := shapes[bi][sizeLog2]
			for pos := 0; pos < sh.BaseWidth; pos++ {
				key := entryKey{batchIdx: bi, sizeLog2: sizeLog2, isExt: false, position: pos}
				entryIndex[key] = g
				entryClaims = append(entryClaims, claimVec(key, shiftOrder[key], claimValues))
				g++
			}
			for pos := 0; pos < sh.ExtWidth; pos++ {
				key := entryKey{batchIdx: bi, sizeLog2: sizeLog2, isExt: true, position: pos}
				entryIndex[key] = g
				entryClaims = append(entryClaims, claimVec(key, shiftOrder[key], claimValues))
				g++
			}
		}
	}

	// Claim maps: the vanishing System's witness/quotient claim ORDER is the
	// order of global.Verifier.WitnessClaims / bucket.QuotientClaims, whose
	// (column, shift) come from WitnessViews / the bucket share views. We
	// re-walk the verifiers to get that order aligned with the (entry, shift).
	witnessMap, quotientMap := buildClaimMaps(sys, colLoc, entryIndex, shiftOrder)

	// zeta coin index: the shared LagrangeEval eval coin.
	zetaCoinIdx := zetaCoinIndex(sys, routing)

	// Transcript rounds.
	rounds := buildCoexistRounds(sys, rt)

	// PCS params: plaintext size = largest opened size; codeword = +inverseRate.
	logPlain := maxSize
	return coexistFixture{
		sys:         sys,
		rt:          rt,
		routing:     routing,
		van:         van,
		logDeriv:    logDeriv,
		hasLogDeriv: len(logDeriv.Queries) > 0,
		logCodeword: codewordSizeLog2(maxSize),
		logPlain:    logPlain,
		numQueries:  len(rt.PCSOpeningProof.InputQueries),
		shapes:      shapes,
		shifts:      shifts,
		roots:       roots,
		entryClaims: entryClaims,
		zetaCoinIdx: zetaCoinIdx,
		witnessMap:  witnessMap,
		quotientMap: quotientMap,
		proof:       rt.PCSOpeningProof,
		rounds:      rounds,
	}
}

func claimVec(key entryKey, order []int, values map[claimCellKey]field.Ext) []field.Ext {
	// order is the per-key shift order; values keyed by (key, shift).
	out := make([]field.Ext, len(order))
	for i, sh := range order {
		out[i] = values[claimCellKey{key, sh}]
	}
	return out
}

func initCoexistShifts(shape fri.Shape) fri.BatchShifts {
	bs := make(fri.BatchShifts, len(shape))
	for i, ss := range shape {
		bs[i] = fri.SizedShifts{
			Base: make([][]int, ss.BaseWidth),
			Ext:  make([][]int, ss.ExtWidth),
		}
	}
	return bs
}

// buildClaimMaps produces the witness/quotient claim maps in the SAME order the
// vanishing System enumerates its flat witness_claims / quotient_claims
// (extractVanishingProofView order: per global.Verifier, WitnessClaims then, per
// bucket, QuotientClaims). Each claim CELL is a LagrangeEval.EvaluationClaims
// entry whose paired Polynomials[k] gives the opened (column, shift); that maps
// to a flat entry index + shift slot. This is the concrete realization of the
// invariant that vanishing claims ARE a re-slicing of entry_claims.
func buildClaimMaps(
	sys *wiop.System,
	colLoc map[wiop.ObjectID]locWithBatchT,
	entryIndex map[entryKey]int,
	shiftOrder map[entryKey][]int,
) (witnessMap, quotientMap []claimRef) {
	// cell ObjectID -> (column view) via the LagrangeEvals that own the cells.
	cellView := map[wiop.ObjectID]*wiop.ColumnView{}
	for _, le := range sys.LagrangeEvals {
		for k, cv := range le.Polynomials {
			cellView[le.EvaluationClaims[k].Context.ID] = cv
		}
	}

	refFor := func(cell *wiop.Cell) claimRef {
		cv, ok := cellView[cell.Context.ID]
		if !ok {
			panic(fmt.Sprintf("coexist: vanishing claim cell %v has no LagrangeEval opening", cell.Context.ID))
		}
		lb := colLoc[cv.Column.Context.ID]
		size := 1 << lb.loc.SizeID
		shift := ((cv.ShiftingOffset % size) + size) % size
		key := entryKey{batchIdx: lb.batchIdx, sizeLog2: lb.loc.SizeID, isExt: lb.loc.IsExt, position: lb.loc.Position}
		entry := entryIndex[key]
		// Shift slot: index of `shift` within the entry's ordered shift list.
		slot := -1
		for i, s := range shiftOrder[key] {
			if s == shift {
				slot = i
				break
			}
		}
		if slot < 0 {
			panic(fmt.Sprintf("coexist: shift %d not found for entry %+v", shift, key))
		}
		return claimRef{entry: entry, shift: slot}
	}

	for _, verifier := range globalVerifiers(sys) {
		for _, cell := range verifier.WitnessClaims {
			witnessMap = append(witnessMap, refFor(cell))
		}
		for _, bucket := range verifier.Buckets {
			for _, cell := range bucket.QuotientClaims {
				quotientMap = append(quotientMap, refFor(cell))
			}
		}
	}
	return witnessMap, quotientMap
}

// zetaCoinIndex returns the flat all_coins index of the shared LagrangeEval eval
// coin (zeta). All LagrangeEvals share this coin (global.Compile's evalCoin).
func zetaCoinIndex(sys *wiop.System, routing codegen.CoinRouting) int {
	if len(sys.LagrangeEvals) == 0 {
		panic("coexist: no LagrangeEvals; cannot locate zeta coin")
	}
	coin, ok := sys.LagrangeEvals[0].EvaluationPoint.(*wiop.CoinField)
	if !ok {
		panic("coexist: LagrangeEval EvaluationPoint is not a CoinField")
	}
	round := coin.Context.ID.Slot()
	pos := coin.Context.ID.Position()
	return routing.RoundCoinOffsets[round] + pos
}

// buildCoexistRounds serializes the transcript into verifier-ray RoundMessage
// shape. For each system round, in order: HasCommitment rounds carry the
// round's Merkle root as an oracle_commitment (matching prover-ray AdvanceRound,
// which absorbs commitment[:] for committed rounds and skips the now-hidden
// columns); public columns and cells carry their raw values. The opening round
// (no columns, no cells) becomes an empty message, leaving the transcript
// positioned exactly where the FRI opener continues.
func buildCoexistRounds(sys *wiop.System, rt *wiop.Runtime) []coexistRound {
	// verifier-ray's replay model has one message round per coin-squeeze phase:
	// round_coin_counts[0] is the pre-round-1 phase (0 coins), so there are
	// len(sys.Rounds)-1 message rounds. The final (opening) round squeezes no
	// coins and absorbs nothing, so it is not emitted; the transcript ends
	// exactly where prover-ray's FRI opener continues (`fs := rt.GetFS()`).
	rounds := make([]coexistRound, 0, len(sys.Rounds)-1)
	for _, r := range sys.Rounds[:len(sys.Rounds)-1] {
		var cr coexistRound
		if r.HasCommitment {
			root, ok := rt.Commitments[r.ID]
			if !ok {
				panic(fmt.Sprintf("coexist: round %d HasCommitment but no root", r.ID))
			}
			c := root
			cr.commitment = &c
		}
		// Public (non-hidden) columns would be absorbed here; the minimal
		// fixture has none (the only columns are committed → hidden). Guard so a
		// future non-minimal fixture fails loudly rather than silently dropping.
		for _, col := range r.Columns {
			if col.Visibility >= wiop.VisibilityOracle {
				panic(fmt.Sprintf("coexist: round %d has a visible column %v; transcript emitter only handles committed+cells", r.ID, col.Context.ID))
			}
		}
		for _, cell := range r.Cells {
			if !rt.HasCellValue(cell) {
				continue
			}
			v := rt.GetCellValue(cell)
			if v.IsBase() {
				b := v.AsBase()
				cr.cells = append(cr.cells, coexistCell{base: &b})
			} else {
				e := v.AsExt()
				cr.cells = append(cr.cells, coexistCell{ext: &e})
			}
		}
		rounds = append(rounds, cr)
	}
	return rounds
}

// codewordSizeLog2 is the FRI codeword-domain log size for a batch whose largest
// committed size is 2^maxSizeLog2: maxSizeLog2 + friLogInverseRate.
func codewordSizeLog2(maxSizeLog2 int) int { return maxSizeLog2 + friLogInverseRate }

// diagnoseCoexist builds the coexisting system, compiles both passes, proves,
// and prints the resulting round structure so the transcript emitter can be
// written against the real shape. Temporary scaffolding; invoked by `-coexist`
// until buildCoexistFixture is complete.
func diagnoseCoexist() {
	pcscompiler.SetFRINumQueriesForTest(1)
	sys, col := buildCoexistSystem()
	global.Compile(sys)
	pcscompiler.Compile(sys)

	rt := runProver(sys, func(rt *wiop.Runtime) {
		rt.AssignColumn(col, concreteBase(elems(7, 99, 7, 7)))
	})

	routing, err := codegen.BuildCoinRouting(sys)
	if err != nil {
		panic(err)
	}
	fmt.Printf("rounds=%d  coinRouting: counts=%v offsets=%v total=%d\n",
		len(sys.Rounds), routing.RoundCoinCounts, routing.RoundCoinOffsets, routing.TotalRoundCoins)
	for _, r := range sys.Rounds {
		fmt.Printf("round %d: HasCommitment=%v  cols=%d  cells=%d  coins=%d\n",
			r.ID, r.HasCommitment, len(r.Columns), len(r.Cells), len(r.Coins))
		for _, c := range r.Columns {
			fmt.Printf("    col %v vis=%d ext=%v size=%d\n", c.Context.ID, c.Visibility, c.IsExtension, c.Module.RuntimeSize(rt))
		}
	}
	batches := pcscompiler.CommittedBatches(sys)
	fmt.Printf("batches=%d\n", len(batches))
	for i, b := range batches {
		_, shape := pcscompiler.GetLayout(b.Round, rt)
		fmt.Printf("  batch %d: round=%d precomp=%v shape=%+v\n", i, b.Round.ID, b.IsPrecomp, shape)
	}
	for _, le := range sys.LagrangeEvals {
		coin, ok := le.EvaluationPoint.(*wiop.CoinField)
		fmt.Printf("  LE polys=%d claims=%d evalCoinOK=%v", len(le.Polynomials), len(le.EvaluationClaims), ok)
		if ok {
			fmt.Printf(" coinID slot=%d pos=%d", coin.Context.ID.Slot(), coin.Context.ID.Position())
		}
		fmt.Println()
	}
	if rt.PCSOpeningProof != nil {
		p := rt.PCSOpeningProof
		fmt.Printf("proof: inputQueries=%d roundRoots=%d finalPoly=%d\n",
			len(p.InputQueries), len(p.FRIProof.RoundRoots), len(p.FRIProof.FinalPoly))
	}
}
