package main

import (
	"bytes"
	"fmt"

	fri "github.com/LFDT-Lineth/lineth-monorepo/prover-ray/crypto/koalabear/fri"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/maths/koalabear/field"
)

// emitFrip serializes a real FRI/PCS opening proof into frip.zig. The Zig test
// reconstructs verify.System (comptime) and verify.Inputs/Proof (runtime) from
// these constants and runs pcs.verify.
//
// Layout of the emitted file:
//   - shapes / shifts as verifier-ray pcs.layout literals (drive System)
//   - roots, entry_claims (flat canonical order), zeta, fold alphas, positions
//   - the OpeningProof: input_queries[query][batch] + running FRI data
func emitFrip(out *bytes.Buffer, fx fripFixture) {
	fmt.Fprintln(out, "// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.")
	fmt.Fprintln(out, "//")
	fmt.Fprintln(out, "// A REAL FRI/PCS opening proof produced by prover-ray's fri package, for the")
	fmt.Fprintln(out, "// verifier-ray cross-check test. Every value here comes from the Go prover.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, `const verifier_ray = @import("verifier_ray");`)
	fmt.Fprintln(out, "const field = verifier_ray.field.koalabear;")
	fmt.Fprintln(out, "const ext = verifier_ray.field.koalabear_ext;")
	fmt.Fprintln(out, "const pcs = verifier_ray.pcs.root;")
	fmt.Fprintln(out, "const layout = pcs.layout;")
	fmt.Fprintln(out, "const verify = pcs.verify;")
	fmt.Fprintln(out, "const tree = pcs.tree;")
	fmt.Fprintln(out, "const pl = pcs.paired_leaf;")
	fmt.Fprintln(out)

	p := fx.params
	// log_final_poly_size = log2(len(FinalPoly)); FinalPoly holds 2^k coeffs.
	logFinal := bitsLen(len(fx.proof.FRIProof.FinalPoly))
	// Params.
	fmt.Fprintf(out, "pub const params = pcs.Params{ .log_codeword_size = %d, .log_plaintext_size = %d, .num_queries = %d, .log_final_poly_size = %d };\n",
		p.LogCodewordSize, p.LogPlainTextSize, p.NumQueries, logFinal)
	fmt.Fprintln(out)

	emitShapes(out, fx.shape)
	emitShifts(out, fx.shifts)
	fmt.Fprintln(out)

	// System (comptime): built from shapes + shifts.
	fmt.Fprintln(out, "pub const system = verify.System{")
	fmt.Fprintln(out, "    .params = params,")
	fmt.Fprintln(out, "    .layout = layout.buildLayout(&shapes, &shifts) catch unreachable,")
	fmt.Fprintln(out, "    .shapes = &shapes,")
	fmt.Fprintln(out, "    .num_batches = 1,")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	// Roots.
	fmt.Fprint(out, "pub const roots = [_]tree.Octuplet{ ")
	emitOctuplet(out, fx.root)
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out)

	emitEntryClaims(out, fx)
	fmt.Fprintln(out)

	// Fiat-Shamir seed state: the transcript state snapshotted BEFORE the first
	// fold challenge is squeezed. The Zig test does `transcript.setState(...)`
	// with this and re-derives fold_alphas + query_positions exactly as the
	// prover did, so those are no longer trusted inputs. fold_alphas and
	// query_positions below are the honest derived values, emitted for the
	// mutation tests' reference (e.g. flipping a position).
	fmt.Fprint(out, "pub const fs_seed_state = ")
	emitOctuplet(out, fx.fsSeedState)
	fmt.Fprintln(out, ";")

	// Zeta, fold alphas, query positions.
	fmt.Fprint(out, "pub const zeta = ")
	emitExt(out, fx.zeta)
	fmt.Fprintln(out, ";")
	fmt.Fprint(out, "pub const fold_alphas = [_]ext.Ext{ ")
	for i, a := range fx.foldAlphas {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitExt(out, a)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprint(out, "pub const query_positions = [_]usize{ ")
	for i, q := range fx.queryPositions {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "%d", q)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out)

	emitProof(out, fx)
}

// emitShapes writes the per-batch declared shapes (one batch).
func emitShapes(out *bytes.Buffer, shape fri.Shape) {
	fmt.Fprintln(out, "const batch0_shape = [_]layout.SizedShape{")
	for _, s := range shape {
		fmt.Fprintf(out, "    .{ .base_width = %d, .ext_width = %d },\n", s.BaseWidth, s.ExtWidth)
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "pub const shapes = [_]layout.Shape{&batch0_shape};")
}

func emitShifts(out *bytes.Buffer, shifts fri.BatchShifts) {
	// Emit each size's base/ext shift lists, then assemble SizedShifts.
	for sizeLog2, ss := range shifts {
		for r, row := range ss.Base {
			fmt.Fprintf(out, "const b0_s%d_base_%d = [_]usize{ %s };\n", sizeLog2, r, intList(row))
		}
		for r, row := range ss.Ext {
			fmt.Fprintf(out, "const b0_s%d_ext_%d = [_]usize{ %s };\n", sizeLog2, r, intList(row))
		}
	}
	fmt.Fprintln(out, "const batch0_shifts = [_]layout.SizedShifts{")
	for sizeLog2, ss := range shifts {
		fmt.Fprint(out, "    .{ .base = &.{")
		for r := range ss.Base {
			if r > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, " &b0_s%d_base_%d", sizeLog2, r)
		}
		fmt.Fprint(out, " }, .ext = &.{")
		for r := range ss.Ext {
			if r > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, " &b0_s%d_ext_%d", sizeLog2, r)
		}
		fmt.Fprintln(out, " } },")
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out, "pub const shifts = [_]layout.BatchShifts{&batch0_shifts};")
}

// emitEntryClaims writes claimed values in the canonical flat order the Zig
// verifier walks: size DESCENDING, batch order, base-then-ext, row order.
func emitEntryClaims(out *bytes.Buffer, fx fripFixture) {
	type col struct{ vals []field.Ext }
	var cols []col

	maxSize := len(fx.shifts) - 1
	for sizeLog2 := maxSize; sizeLog2 >= 0; sizeLog2-- {
		if sizeLog2 >= len(fx.shifts) {
			continue
		}
		ss := fx.shifts[sizeLog2]
		cv := fx.claimed[sizeLog2]
		for r := range ss.Base {
			cols = append(cols, col{vals: cv.Base[r]})
		}
		for r := range ss.Ext {
			cols = append(cols, col{vals: cv.Ext[r]})
		}
	}

	for i, c := range cols {
		fmt.Fprintf(out, "const claim_col_%d = [_]ext.Ext{ ", i)
		for j, v := range c.vals {
			if j > 0 {
				fmt.Fprint(out, ", ")
			}
			emitExt(out, v)
		}
		fmt.Fprintln(out, " };")
	}
	fmt.Fprint(out, "pub const entry_claims = [_][]const ext.Ext{ ")
	for i := range cols {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&claim_col_%d", i)
	}
	fmt.Fprintln(out, " };")
}

func emitProof(out *bytes.Buffer, fx fripFixture) {
	proof := fx.proof

	// Round roots.
	fmt.Fprint(out, "pub const round_roots = [_]tree.Octuplet{ ")
	for i, r := range proof.FRIProof.RoundRoots {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitOctuplet(out, r)
	}
	fmt.Fprintln(out, " };")

	// Final poly.
	fmt.Fprint(out, "pub const final_poly = [_]ext.Ext{ ")
	for i, c := range proof.FRIProof.FinalPoly {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitExt(out, c)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out)

	// Input queries: input_queries[query][batch]. One batch here.
	for q, iq := range proof.InputQueries {
		for b, opening := range iq {
			emitInputTreeOpening(out, q, b, opening)
		}
	}
	// Assemble per-query batch arrays then the outer array.
	fmt.Fprintln(out, "pub const input_queries = assembleInputQueries();")
	fmt.Fprintln(out, "fn assembleInputQueries() []const []const pl.InputTreeOpening {")
	fmt.Fprintf(out, "    const S = struct {\n")
	for q := range proof.InputQueries {
		fmt.Fprintf(out, "        const q%d = [_]pl.InputTreeOpening{ ", q)
		for b := range proof.InputQueries[q] {
			if b > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, "iq_%d_%d", q, b)
		}
		fmt.Fprintln(out, " };")
	}
	fmt.Fprint(out, "        const all = [_][]const pl.InputTreeOpening{ ")
	for q := range proof.InputQueries {
		if q > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&q%d", q)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "    return &S.all;")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)

	// Running queries: running_queries[query][round-1] = one Branch.
	for q, rq := range proof.FRIProof.RunningQueries {
		for layerIdx, layer := range rq {
			// Each QueryLayer is []Branch; the running path uses a single branch.
			emitBranch(out, q, layerIdx, layer[0])
		}
	}
	fmt.Fprintln(out, "pub const running_queries = assembleRunningQueries();")
	fmt.Fprintln(out, "fn assembleRunningQueries() []const []const tree.Branch {")
	fmt.Fprintln(out, "    const S = struct {")
	for q, rq := range proof.FRIProof.RunningQueries {
		fmt.Fprintf(out, "        const q%d = [_]tree.Branch{ ", q)
		for layerIdx := range rq {
			if layerIdx > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, "rq_%d_%d", q, layerIdx)
		}
		fmt.Fprintln(out, " };")
	}
	fmt.Fprint(out, "        const all = [_][]const tree.Branch{ ")
	for q := range proof.FRIProof.RunningQueries {
		if q > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "&q%d", q)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "    return &S.all;")
	fmt.Fprintln(out, "}")
}

func emitInputTreeOpening(out *bytes.Buffer, q, b int, opening fri.InputTreeOpening) {
	// Siblings.
	fmt.Fprintf(out, "const iq_%d_%d_sibs = [_]tree.Octuplet{ ", q, b)
	for i, s := range opening.Siblings {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitOctuplet(out, s)
	}
	fmt.Fprintln(out, " };")

	// Leaves (each an optional RowPair). Emit row storage first.
	for i, leaf := range opening.Leaves {
		if leaf == nil {
			continue
		}
		emitRowPairStorage(out, fmt.Sprintf("iq_%d_%d_leaf_%d", q, b, i), *leaf)
	}
	fmt.Fprintf(out, "const iq_%d_%d_leaves = [_]?pl.RowPair{ ", q, b)
	for i, leaf := range opening.Leaves {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		if leaf == nil {
			fmt.Fprint(out, "null")
		} else {
			fmt.Fprintf(out, "iq_%d_%d_leaf_%d", q, b, i)
		}
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintf(out, "const iq_%d_%d = pl.InputTreeOpening{ .siblings = &iq_%d_%d_sibs, .leaves = &iq_%d_%d_leaves };\n", q, b, q, b, q, b)
}

func emitRowPairStorage(out *bytes.Buffer, name string, pair fri.RowPair) {
	for side := 0; side < 2; side++ {
		emitRowStorage(out, fmt.Sprintf("%s_r%d", name, side), pair[side])
	}
	fmt.Fprintf(out, "const %s = pl.RowPair{ pl.RowOpening{ .base = &%s_r0_base, .ext = &%s_r0_ext }, pl.RowOpening{ .base = &%s_r1_base, .ext = &%s_r1_ext } };\n",
		name, name, name, name, name)
}

func emitRowStorage(out *bytes.Buffer, name string, row fri.RowOpening) {
	fmt.Fprintf(out, "const %s_base = [_]field.Element{ ", name)
	for i, b := range row.Base {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "field.Element.init(%d)", elemVal(b))
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintf(out, "const %s_ext = [_]ext.Ext{ ", name)
	for i, e := range row.Ext {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitExt(out, e)
	}
	fmt.Fprintln(out, " };")
}

func emitBranch(out *bytes.Buffer, q, layerIdx int, branch fri.Branch) {
	fmt.Fprintf(out, "const rq_%d_%d_sibs = [_]tree.Octuplet{ ", q, layerIdx)
	for i, s := range branch.Siblings {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		emitOctuplet(out, s)
	}
	fmt.Fprintln(out, " };")
	fmt.Fprintf(out, "const rq_%d_%d_aux = [_]?tree.Octuplet{ ", q, layerIdx)
	for i, a := range branch.AuxSiblings {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		if a == nil {
			fmt.Fprint(out, "null")
		} else {
			emitOctuplet(out, *a)
		}
	}
	fmt.Fprintln(out, " };")
	fmt.Fprint(out, "const rq_"+fmt.Sprintf("%d_%d", q, layerIdx)+"_leaf = ")
	emitOctuplet(out, branch.Leaf)
	fmt.Fprintln(out, ";")
	fmt.Fprintf(out, "const rq_%d_%d = tree.Branch{ .leaf = rq_%d_%d_leaf, .siblings = &rq_%d_%d_sibs, .aux_siblings = &rq_%d_%d_aux };\n",
		q, layerIdx, q, layerIdx, q, layerIdx, q, layerIdx)
}

// ── scalar emit helpers ──────────────────────────────────────────────────────

func emitOctuplet(out *bytes.Buffer, o field.Octuplet) {
	fmt.Fprint(out, "tree.Octuplet{ ")
	for i := 0; i < 8; i++ {
		if i > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "field.Element.init(%d)", elemVal(o[i]))
	}
	fmt.Fprint(out, " }")
}

func emitExt(out *bytes.Buffer, e field.Ext) {
	c := extCoords(e)
	fmt.Fprintf(out, "ext.Ext.fromUints(.{ %d, %d, %d, %d, %d, %d })", c[0], c[1], c[2], c[3], c[4], c[5])
}

func intList(xs []int) string {
	var b bytes.Buffer
	for i, x := range xs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%d", x)
	}
	return b.String()
}

func bitsLen(n int) int {
	l := 0
	for (1 << l) < n {
		l++
	}
	return l
}

// elemVal returns the canonical (non-Montgomery) value of a base element.
func elemVal(e field.Element) uint64 {
	return e.Uint64()
}

// extCoords flattens an extension element to [B0.A0, B0.A1, B1.A0, B1.A1,
// B2.A0, B2.A1] canonical values — the same order verifier-ray's
// ext.Ext.fromUints expects.
func extCoords(e field.Ext) [6]uint64 {
	return [6]uint64{
		e.B0.A0.Uint64(), e.B0.A1.Uint64(),
		e.B1.A0.Uint64(), e.B1.A1.Uint64(),
		e.B2.A0.Uint64(), e.B2.A1.Uint64(),
	}
}
