buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
  dependencies {
    classpath(libs.jreleaser)
  }
}

apply plugin: 'java-library'

repositories {
  mavenCentral()
  maven {
    url 'https://artifacts.consensys.net/public/teku/maven/'
    content { includeGroupAndSubgroups('tech.pegasys') }
  }
  maven {
    name = 'linea-besu'
    url = "https://artifacts.consensys.net/public/linea-besu/maven/"
  }
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

group = 'build.linea'
description = 'Lineth chain security interfaces'
// publishing.gradle uses project.artifactId when set (or else falling back to project.name)
ext.artifactId = 'sequencer-interfaces'

jar { enabled = true }

dependencies {
  api project(':jvm-libs:linea:core:signer-interfaces')

  // Besu Plugin API and core dependencies
  compileOnly "org.hyperledger.besu:besu-plugin-api:${rootProject.ext.resolveBesuVersion()}"
  compileOnly "org.hyperledger.besu:besu-evm:${rootProject.ext.resolveBesuVersion()}"
  compileOnly "org.hyperledger.besu:besu-datatypes:${rootProject.ext.resolveBesuVersion()}"
}

apply from: rootProject.file("gradle/publishing.gradle")

tasks.withType(GenerateModuleMetadata).configureEach {
  suppressedValidationErrors.add('enforced-platform')
}
