name: rollup-spec-testing

permissions:
  contents: read
  actions: read

on: workflow_call

concurrency:
  group: rollup-spec-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-rollup-spec-tests:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-med
    name: Run Rollup Spec Tests
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup python environment
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install pytest jsonschema

      - name: Run schema conformance test
        shell: bash
        run: |
          python -m pytest rollup_spec/prover_io/schemas/fixture_schema_conformance_test.py

      - name: Run proof io test
        shell: bash
        run: |
           python -m pytest rollup_spec/proof_io_v1_test.py
